/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.BXHController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.BXH;
import model.User;

/**
 *
 * @author lampn
 */
public class FrmBXH extends javax.swing.JInternalFrame {
    /**
     * Creates new form FrmBXH
     */
    User user ; 
    DefaultTableModel tableBXHModel;
    List<BXH> BXHList = new ArrayList<>();

    public FrmBXH(User us) {
        initComponents();
        user = us ; 
        tableBXHModel = (DefaultTableModel) jtbBXH.getModel();
        ShowBXH();
    }
    
    public void ShowBXH() {
        BXHList = BXHController.findAll();

        // Đưa số Row của table về 0
        tableBXHModel.setRowCount(0);
           System.out.println(cbVong.getSelectedItem().toString());
        BXHList.forEach(bxh -> {
            if(bxh.getTenvong().equals(cbVong.getSelectedItem().toString())) {
            tableBXHModel.addRow(new Object[]{bxh.getTenvong(), bxh.getVitri(), bxh.getTendoi(),
                bxh.getSotran(), bxh.getSotrangthang(), bxh.getSobanthua(), 
                bxh.getSotranhoa(), bxh.getSobanthang(), bxh.getSobanthua(), bxh.getHieuso(), bxh.getDiem()});
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jtbBXH = new javax.swing.JTable();
        cbVong = new javax.swing.JComboBox<>();
        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jtbBXH.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jtbBXH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên vòng", "Vị trí", "Tên CLB", "Số trận", "Số trận thắng", "Số trận thua", "Số trận hòa", "Số bàn thắng", "Số bàn thua", "Hiệu số", "Điểm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbBXH.setRowHeight(20);
        jScrollPane5.setViewportView(jtbBXH);

        cbVong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vòng", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11" }));
        cbVong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVongActionPerformed(evt);
            }
        });

        btnCancel.setText("Quay lại");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("BẢNG XẾP HẠNG THEO TỪNG VÒNG ĐẤU");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbVong, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160)
                        .addComponent(jLabel2)
                        .addGap(0, 279, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbVong, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbVongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVongActionPerformed
        // TODO add your handling code here:
                BXHList = BXHController.findAll();

        // Đưa số Row của table về 0
        tableBXHModel.setRowCount(0);
        BXHList.forEach(bxh -> {
            System.out.println(bxh.getTenvong());
            if(bxh.getTenvong().equals(cbVong.getSelectedItem().toString()))
            {
                tableBXHModel.addRow(new Object[]{bxh.getTenvong(), bxh.getVitri(), bxh.getTendoi(),
                    bxh.getSotran(), bxh.getSotrangthang(), bxh.getSobanthua(),
                    bxh.getSotranhoa(), bxh.getSobanthang(), bxh.getSobanthua(), bxh.getHieuso(), bxh.getDiem()});
            }
        });
    }//GEN-LAST:event_cbVongActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> cbVong;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jtbBXH;
    // End of variables declaration//GEN-END:variables
}
