/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.ClLBController;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import machine.learning.MyDecisionTreeModel;
import model.CLB;
import machine.learning.MyDecisionTreeModel;
import model.User;
import weka.classifiers.trees.J48;

/**
 *
 * @author lampn
 */
public class FrmDuDoan extends javax.swing.JInternalFrame {
    User user ;
    /**
     * Creates new form FrmDuDoan
     */
    public FrmDuDoan(User us) {
        initComponents();
        user = us ; 
        ShowCLBdd1();
        ShowCLBdd2();
    }
    private void ShowCLBdd1() {
        List<CLB> ClbList = ClLBController.findAll();
        cbCLBdd1.removeAllItems();
        ClbList.forEach(clb -> {
            cbCLBdd1.addItem(clb.getTendoi());
        });
    }
    private void ShowCLBdd2() {
        List<CLB> ClbList = ClLBController.findAll();
        cbCLBdd2.removeAllItems();
        ClbList.forEach(clb -> {
            cbCLBdd2.addItem(clb.getTendoi());
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbCLBdd2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cbCLBdd1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jtfPredict = new javax.swing.JTextField();
        btnThoat = new javax.swing.JButton();

        cbCLBdd2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbCLBdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCLBdd2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Dice-icon.png"))); // NOI18N
        jLabel1.setText("DỰ ĐOÁN");

        cbCLBdd1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbCLBdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCLBdd1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Dự đoán");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtfPredict.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtfPredict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPredictActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(231, 231, 231)
                                .addComponent(cbCLBdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtfPredict, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(cbCLBdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(450, 450, 450)
                                .addComponent(jLabel1)))
                        .addGap(0, 224, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCLBdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCLBdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPredict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCLBdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCLBdd2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCLBdd2ActionPerformed

    private void cbCLBdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCLBdd1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbCLBdd1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            MyDecisionTreeModel model = new MyDecisionTreeModel("D:\\workspace\\lampn182628\\lap_trinh_nang_cao\\project\\football_management_ltnc\\bongda.arff",
                "-C 0.25 -M 2",null);
            model.buildDecisionTree1();
            model.tree = (J48) model.loadModel("D:\\workspace\\lampn182628\\lap_trinh_nang_cao\\project\\football_management_ltnc\\decisiontree.model");
            List<String> strList = new ArrayList<>();
            strList = model.predictClassLabel(model.testset);
            int a = (int)(Math.random() * 7);
            System.out.println("a = " +  a + " str = " + strList.get(a));
            jtfPredict.setText(strList.get(a));
        } catch (Exception ex) {
            Logger.getLogger(FrmDuDoan.class.getName()).log(Level.SEVERE, null, ex);
//            Logger.getLogger(DuDoanFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtfPredictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPredictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPredictActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> cbCLBdd1;
    private javax.swing.JComboBox<String> cbCLBdd2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jtfPredict;
    // End of variables declaration//GEN-END:variables
}
